# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='node.proto',
  package='',
  serialized_pb='\n\nnode.proto\"}\n\x04Node\x12\x0e\n\x06nodeid\x18\x01 \x02(\t\x12#\n\x05state\x18\x02 \x02(\x0e\x32\x0b.Node.State:\x07PLANNED\"@\n\x05State\x12\x0b\n\x07PLANNED\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\x0e\n\nINCOMPLETE\x10\x02\x12\x0b\n\x07RETIRED\x10\x03')



_NODE_STATE = descriptor.EnumDescriptor(
  name='State',
  full_name='Node.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PLANNED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AVAILABLE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INCOMPLETE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RETIRED', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=75,
  serialized_end=139,
)


_NODE = descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nodeid', full_name='Node.nodeid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='Node.state', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODE_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=139,
)

_NODE.fields_by_name['state'].enum_type = _NODE_STATE
_NODE_STATE.containing_type = _NODE;
DESCRIPTOR.message_types_by_name['Node'] = _NODE

class Node(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODE
  
  # @@protoc_insertion_point(class_scope:Node)

# @@protoc_insertion_point(module_scope)
