# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='repeated_field.proto',
  package='',
  serialized_pb='\n\x14repeated_field.proto\"\x1c\n\x0bTestMessage\x12\r\n\x05notes\x18\x01 \x03(\t')




_TESTMESSAGE = descriptor.Descriptor(
  name='TestMessage',
  full_name='TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='notes', full_name='TestMessage.notes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE

class TestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMESSAGE
  
  # @@protoc_insertion_point(class_scope:TestMessage)

# @@protoc_insertion_point(module_scope)
